//! Lifepath roller — WP-504.
//!
//! Wires the authored RON tables from `content/tables/lifepath/` (loaded by
//! WP-214's [`crate::catalog::lifepath`] loaders) together with the
//! deterministic [`crate::Rng`] to produce a complete, randomised
//! [`Lifepath`] record for a given [`Role`].
//!
//! # Roll procedure
//!
//! All shared tables (pp.43–53) are rolled first; then the role-specific
//! lifepath file (pp.54–69) is loaded and rolled. Relationship beacons
//! (friends, enemies, tragic loves) each get at least one entry generated by
//! rolling d10 on the appropriate table (pp.51–52). Names default to
//! flavour-text placeholders ("Friend 1", "Enemy 1", "Lover 1") per the
//! WP-504 spec since the rulebook does not print a canonical name list for
//! these NPCs.
//!
//! # Determinism
//!
//! Every dice call goes through the caller-supplied `rng: &mut Rng`. The same
//! seed always produces the same [`Lifepath`]. See [`crate::rng`].
//!
//! # Rulebook references
//!
//! See pp.43–69 ("Tales from The Street").

use crate::catalog::lifepath::{
    load_affectations_table, load_clothing_table, load_cultural_origin_table, load_enemies_table,
    load_family_background_table, load_family_crisis_table, load_friends_table,
    load_hairstyle_table, load_life_goals_table, load_motivations_table, load_personality_table,
    load_role_lifepath, load_tragic_loves_table, BeaconKind, ExecLifepath, FamilyBackground,
    FixerLifepath, LawmanLifepath, Lifepath, MediaLifepath, MedtechLifepath, NetrunnerLifepath,
    NomadLifepath, RelationshipBeacon, RockerboyLifepath, RoleLifepath, RoleLifepathTables,
    SoloLifepath, TechLifepath,
};
use crate::character::data::Role;
use crate::dice::{d10, d6};
use crate::error::RulesError;
use crate::rng::Rng;
use std::path::Path;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Roll a complete Lifepath for the given role using the authored RON tables.
///
/// Loads every shared lifepath table from `tables_dir` (e.g.
/// `content/tables/lifepath/`), rolls on each using `rng`, then loads and
/// rolls the role-specific lifepath file. Returns a fully populated
/// [`Lifepath`] struct.
///
/// Friends, enemies, and tragic loves each produce **at least one** beacon.
/// Additional beacons are added for each positive result of `d10 - 7`
/// (minimum 0), matching the pp.51–52 book mechanic.
///
/// # Errors
///
/// Returns [`RulesError::CatalogLoadFailed`] if any RON file cannot be read
/// or parsed. Returns [`RulesError::InvalidLifepathRoll`] if a table lookup
/// returns `None` — this indicates a corrupt content file or a test-fixture
/// bug.
///
/// # See pp.43–69
pub fn roll_lifepath(role: Role, tables_dir: &Path, rng: &mut Rng) -> Result<Lifepath, RulesError> {
    // --- Shared tables (pp.43–53) ------------------------------------------

    // Cultural origin (p.45) — d10.
    let cultural_origin_table =
        load_cultural_origin_table(&tables_dir.join("cultural_origin.ron"))?;
    let co_roll = d10(rng);
    let co_row =
        cultural_origin_table
            .lookup(co_roll)
            .ok_or_else(|| RulesError::InvalidLifepathRoll {
                table: "cultural_origin".into(),
                roll: co_roll,
            })?;
    let cultural_region = co_row.region.clone();
    // Pick the first language from the list as a deterministic default.
    // See pp.43-69: the book says "pick one"; we default to the first entry
    // for the deterministic roller — a higher-level selection UI can override.
    let language_spoken = co_row.languages.first().cloned().unwrap_or_default();

    // Personality (p.46) — d10.
    let personality_table = load_personality_table(&tables_dir.join("personality.ron"))?;
    let p_roll = d10(rng);
    let personality = personality_table
        .lookup(p_roll)
        .ok_or_else(|| RulesError::InvalidLifepathRoll {
            table: "personality".into(),
            roll: p_roll,
        })?
        .clone();

    // Clothing style (p.47) — d10.
    let clothing_table = load_clothing_table(&tables_dir.join("clothing.ron"))?;
    let cl_roll = d10(rng);
    let clothing_style = clothing_table
        .lookup(cl_roll)
        .ok_or_else(|| RulesError::InvalidLifepathRoll {
            table: "clothing".into(),
            roll: cl_roll,
        })?
        .clone();

    // Hairstyle (p.47) — d10.
    let hairstyle_table = load_hairstyle_table(&tables_dir.join("hairstyle.ron"))?;
    let hs_roll = d10(rng);
    let hairstyle = hairstyle_table
        .lookup(hs_roll)
        .ok_or_else(|| RulesError::InvalidLifepathRoll {
            table: "hairstyle".into(),
            roll: hs_roll,
        })?
        .clone();

    // Affectations (p.47) — d10.
    let affectations_table = load_affectations_table(&tables_dir.join("affectations.ron"))?;
    let aff_roll = d10(rng);
    let affectations = affectations_table
        .lookup(aff_roll)
        .ok_or_else(|| RulesError::InvalidLifepathRoll {
            table: "affectations".into(),
            roll: aff_roll,
        })?
        .clone();

    // Motivations / What Do You Value Most? (p.48) — d10.
    let motivations_table = load_motivations_table(&tables_dir.join("motivations.ron"))?;
    let mot_roll = d10(rng);
    let motivation = motivations_table
        .lookup(mot_roll)
        .ok_or_else(|| RulesError::InvalidLifepathRoll {
            table: "motivations".into(),
            roll: mot_roll,
        })?
        .clone();

    // Family background (p.49) — d10.
    let family_bg_table = load_family_background_table(&tables_dir.join("family_background.ron"))?;
    let fb_roll = d10(rng);
    let fb_row =
        family_bg_table
            .lookup(fb_roll)
            .ok_or_else(|| RulesError::InvalidLifepathRoll {
                table: "family_background".into(),
                roll: fb_roll,
            })?;
    // childhood_environment, feelings_about_people, most_valued_person, and
    // most_valued_possession (pp.48, 50) are in sub-sections of pp.48-50 that
    // are not yet represented as separate RON tables in WP-214's content.
    // Per the WP-504 spec these are left blank; future content PRs can add them.
    let family_background = FamilyBackground {
        original_background: fb_row.label.clone(),
        description: fb_row.description.clone(),
        childhood_environment: String::new(),
        feelings_about_people: String::new(),
        most_valued_person: String::new(),
        most_valued_possession: String::new(),
    };

    // Family crisis (p.50) — d10.
    let family_crisis_table = load_family_crisis_table(&tables_dir.join("family_crisis.ron"))?;
    let fc_roll = d10(rng);
    let family_crisis = family_crisis_table
        .lookup(fc_roll)
        .ok_or_else(|| RulesError::InvalidLifepathRoll {
            table: "family_crisis".into(),
            roll: fc_roll,
        })?
        .clone();

    // Life goals (p.53) — d10.
    let life_goals_table = load_life_goals_table(&tables_dir.join("life_goals.ron"))?;
    let lg_roll = d10(rng);
    let life_goal = life_goals_table
        .lookup(lg_roll)
        .ok_or_else(|| RulesError::InvalidLifepathRoll {
            table: "life_goals".into(),
            roll: lg_roll,
        })?
        .clone();

    // Friends (p.51) — at least 1 + (d10 - 7, min 0) more.
    let friends_table = load_friends_table(&tables_dir.join("friends.ron"))?;
    let friends = roll_beacons(&friends_table, BeaconKind::Friend, "Friend", rng)?;

    // Enemies (p.51) — at least 1 + (d10 - 7, min 0) more.
    let enemies_table = load_enemies_table(&tables_dir.join("enemies.ron"))?;
    let enemies = roll_beacons(&enemies_table, BeaconKind::Enemy, "Enemy", rng)?;

    // Tragic loves (p.52) — at least 1 + (d10 - 7, min 0) more.
    let tragic_loves_table = load_tragic_loves_table(&tables_dir.join("tragic_loves.ron"))?;
    let tragic_loves = roll_beacons(&tragic_loves_table, BeaconKind::Lover, "Lover", rng)?;

    // --- Role-specific lifepath (pp.54–69) ----------------------------------

    let role_specific = roll_role_lifepath(role, tables_dir, rng)?;

    Ok(Lifepath {
        cultural_region,
        language_spoken,
        personality,
        clothing_style,
        hairstyle,
        affectations,
        motivation,
        life_goal,
        family_background,
        family_crisis,
        friends,
        enemies,
        tragic_loves,
        role_specific,
    })
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/// Roll one or more relationship beacons from a table.
///
/// Always produces at least one beacon. Additional beacons are added for
/// each positive result of `d10 - 7` (minimum 0), matching the pp.51–52
/// book mechanic. Names are placeholder strings ("Friend 1", "Enemy 1", …)
/// since the rulebook does not list canonical NPC names in these tables.
/// The LLM narrator layer or a player-facing UI assigns real names.
///
/// See pp.51–52.
fn roll_beacons(
    table: &crate::catalog::lifepath::LifepathTable<String>,
    kind: BeaconKind,
    label: &str,
    rng: &mut Rng,
) -> Result<Vec<RelationshipBeacon>, RulesError> {
    // Total count = 1 mandatory + max(d10 - 7, 0).
    let extra_roll = d10(rng);
    let extra = if extra_roll > 7 {
        (extra_roll - 7) as usize
    } else {
        0
    };
    let count = 1 + extra;

    let mut beacons = Vec::with_capacity(count);
    for i in 1..=count {
        let roll = d10(rng);
        let note = table
            .lookup(roll)
            .ok_or_else(|| RulesError::InvalidLifepathRoll {
                table: label.to_lowercase(),
                roll,
            })?
            .clone();
        beacons.push(RelationshipBeacon {
            // Placeholder name — see WP-504 spec: "use 'Friend 1', 'Friend 2'
            // placeholders". See pp.59+.
            name: format!("{label} {i}"),
            kind,
            note,
        });
    }
    Ok(beacons)
}

/// Roll a single sub-table from a [`RoleLifepathTables`] set.
///
/// Uses `roll_fn` to generate a roll value, then looks it up in the named
/// sub-table. Returns [`RulesError::CatalogLoadFailed`] if the sub-table is
/// absent and [`RulesError::InvalidLifepathRoll`] if the roll is out of range.
///
/// See pp.54–69.
fn roll_sub_table(
    role_tables: &RoleLifepathTables,
    table_name: &str,
    roll_fn: fn(&mut Rng) -> u8,
    rng: &mut Rng,
) -> Result<String, RulesError> {
    let table = role_tables
        .get(table_name)
        .ok_or_else(|| RulesError::CatalogLoadFailed {
            path: std::path::PathBuf::from(format!("<role_lifepath>/{table_name}")),
            source: format!("sub-table '{table_name}' not found in role file"),
        })?;
    let roll = roll_fn(rng);
    table
        .lookup(roll)
        .ok_or_else(|| RulesError::InvalidLifepathRoll {
            table: table_name.to_string(),
            roll,
        })
        .cloned()
}

/// Load and roll all role-specific sub-tables for the given role.
///
/// Dispatches to the per-role helper based on `role`. Each helper loads the
/// correct RON file from `tables_dir` and rolls every sub-table.
///
/// See pp.54–69.
fn roll_role_lifepath(
    role: Role,
    tables_dir: &Path,
    rng: &mut Rng,
) -> Result<RoleLifepath, RulesError> {
    let role_filename = match role {
        Role::Rockerboy => "rockerboy.ron",
        Role::Solo => "solo.ron",
        Role::Netrunner => "netrunner.ron",
        Role::Tech => "tech.ron",
        Role::Medtech => "medtech.ron",
        Role::Media => "media.ron",
        Role::Lawman => "lawman.ron",
        Role::Exec => "exec.ron",
        Role::Fixer => "fixer.ron",
        Role::Nomad => "nomad.ron",
    };
    let role_tables = load_role_lifepath(&tables_dir.join(role_filename))?;

    match role {
        Role::Rockerboy => roll_rockerboy(&role_tables, rng),
        Role::Solo => roll_solo(&role_tables, rng),
        Role::Netrunner => roll_netrunner(&role_tables, rng),
        Role::Tech => roll_tech(&role_tables, rng),
        Role::Medtech => roll_medtech(&role_tables, rng),
        Role::Media => roll_media(&role_tables, rng),
        Role::Lawman => roll_lawman(&role_tables, rng),
        Role::Exec => roll_exec(&role_tables, rng),
        Role::Fixer => roll_fixer(&role_tables, rng),
        Role::Nomad => roll_nomad(&role_tables, rng),
    }
}

/// Roll the Rockerboy lifepath (p.54).
///
/// "Are You in a Group or a Solo Act?" and "Were You Once in a Group?" are
/// choose-only on p.54 — no roll table. `group_or_solo` defaults to "Solo
/// Act" and `were_in_group` to blank ("no") for the roller; a player-facing
/// UI should let the player choose. `why_left` is rolled regardless (only
/// meaningful when `were_in_group` is set). See pp.43-69.
fn roll_rockerboy(
    role_tables: &RoleLifepathTables,
    rng: &mut Rng,
) -> Result<RoleLifepath, RulesError> {
    let rockerboy_type = roll_sub_table(role_tables, "rockerboy_type", d10, rng)?;
    let venue = roll_sub_table(role_tables, "venue", d6, rng)?;
    let whos_gunning = roll_sub_table(role_tables, "whos_gunning", d6, rng)?;
    let why_left = roll_sub_table(role_tables, "why_left", d6, rng)?;

    Ok(RoleLifepath::Rockerboy(RockerboyLifepath {
        rockerboy_type,
        group_or_solo: "Solo Act".to_string(),
        were_in_group: String::new(),
        why_left,
        venue,
        whos_gunning,
    }))
}

/// Roll the Solo lifepath (p.55).
fn roll_solo(role_tables: &RoleLifepathTables, rng: &mut Rng) -> Result<RoleLifepath, RulesError> {
    let solo_type = roll_sub_table(role_tables, "solo_type", d6, rng)?;
    let moral_compass = roll_sub_table(role_tables, "moral_compass", d6, rng)?;
    let whos_gunning = roll_sub_table(role_tables, "whos_gunning", d6, rng)?;
    let operational_territory = roll_sub_table(role_tables, "operational_territory", d6, rng)?;

    Ok(RoleLifepath::Solo(SoloLifepath {
        solo_type,
        moral_compass,
        whos_gunning,
        operational_territory,
    }))
}

/// Roll the Netrunner lifepath (pp.56–57).
///
/// "Got a Partner, or Do You Work Alone?" is choose-only on p.56; defaulted
/// to "Work Alone" for the roller. `partner` is rolled regardless (only
/// meaningful when a partner is chosen). See pp.43-69.
fn roll_netrunner(
    role_tables: &RoleLifepathTables,
    rng: &mut Rng,
) -> Result<RoleLifepath, RulesError> {
    let runner_type = roll_sub_table(role_tables, "runner_type", d6, rng)?;
    let workspace = roll_sub_table(role_tables, "workspace", d6, rng)?;
    let other_clients = roll_sub_table(role_tables, "other_clients", d6, rng)?;
    let program_source = roll_sub_table(role_tables, "program_source", d6, rng)?;
    let whos_gunning = roll_sub_table(role_tables, "whos_gunning", d6, rng)?;
    let partner = roll_sub_table(role_tables, "partner", d6, rng)?;

    Ok(RoleLifepath::Netrunner(NetrunnerLifepath {
        runner_type,
        partner_or_alone: "Work Alone".to_string(),
        partner,
        workspace,
        other_clients,
        program_source,
        whos_gunning,
    }))
}

/// Roll the Tech lifepath (pp.58–59).
///
/// "Got a Partner, or Do You Work Alone?" is choose-only on p.58; defaulted
/// to "Work Alone" for the roller. See pp.43-69.
fn roll_tech(role_tables: &RoleLifepathTables, rng: &mut Rng) -> Result<RoleLifepath, RulesError> {
    let tech_type = roll_sub_table(role_tables, "tech_type", d10, rng)?;
    let workspace = roll_sub_table(role_tables, "workspace", d6, rng)?;
    let main_clients = roll_sub_table(role_tables, "main_clients", d6, rng)?;
    let supply_source = roll_sub_table(role_tables, "supply_source", d6, rng)?;
    let whos_gunning = roll_sub_table(role_tables, "whos_gunning", d6, rng)?;
    let partner = roll_sub_table(role_tables, "partner", d6, rng)?;

    Ok(RoleLifepath::Tech(TechLifepath {
        tech_type,
        workspace,
        partner_or_alone: "Work Alone".to_string(),
        partner,
        main_clients,
        supply_source,
        whos_gunning,
    }))
}

/// Roll the Medtech lifepath (pp.60–61).
///
/// "Got a Partner, or Do You Work Alone?" is choose-only on p.60; defaulted
/// to "Work Alone" for the roller. See pp.43-69.
fn roll_medtech(
    role_tables: &RoleLifepathTables,
    rng: &mut Rng,
) -> Result<RoleLifepath, RulesError> {
    let medtech_type = roll_sub_table(role_tables, "medtech_type", d10, rng)?;
    let workspace = roll_sub_table(role_tables, "workspace", d6, rng)?;
    let main_clients = roll_sub_table(role_tables, "main_clients", d6, rng)?;
    let supply_source = roll_sub_table(role_tables, "supply_source", d6, rng)?;
    let partner = roll_sub_table(role_tables, "partner", d6, rng)?;

    Ok(RoleLifepath::Medtech(MedtechLifepath {
        medtech_type,
        partner_or_alone: "Work Alone".to_string(),
        partner,
        workspace,
        main_clients,
        supply_source,
    }))
}

/// Roll the Media lifepath (p.62).
fn roll_media(role_tables: &RoleLifepathTables, rng: &mut Rng) -> Result<RoleLifepath, RulesError> {
    let media_type = roll_sub_table(role_tables, "media_type", d6, rng)?;
    let how_published = roll_sub_table(role_tables, "how_published", d6, rng)?;
    let ethics = roll_sub_table(role_tables, "ethics", d6, rng)?;
    let story_types = roll_sub_table(role_tables, "story_types", d6, rng)?;

    Ok(RoleLifepath::Media(MediaLifepath {
        media_type,
        how_published,
        ethics,
        story_types,
    }))
}

/// Roll the Lawman lifepath (p.65).
fn roll_lawman(
    role_tables: &RoleLifepathTables,
    rng: &mut Rng,
) -> Result<RoleLifepath, RulesError> {
    let position = roll_sub_table(role_tables, "position", d6, rng)?;
    let jurisdiction = roll_sub_table(role_tables, "jurisdiction", d6, rng)?;
    let corruption = roll_sub_table(role_tables, "corruption", d6, rng)?;
    let whos_gunning = roll_sub_table(role_tables, "whos_gunning", d6, rng)?;
    let major_target = roll_sub_table(role_tables, "major_target", d6, rng)?;

    Ok(RoleLifepath::Lawman(LawmanLifepath {
        position,
        jurisdiction,
        corruption,
        whos_gunning,
        major_target,
    }))
}

/// Roll the Exec lifepath (pp.63–64).
fn roll_exec(role_tables: &RoleLifepathTables, rng: &mut Rng) -> Result<RoleLifepath, RulesError> {
    let corp_type = roll_sub_table(role_tables, "corp_type", d10, rng)?;
    let division = roll_sub_table(role_tables, "division", d6, rng)?;
    let corp_ethics = roll_sub_table(role_tables, "corp_ethics", d6, rng)?;
    let corp_location = roll_sub_table(role_tables, "corp_location", d6, rng)?;
    let whos_gunning = roll_sub_table(role_tables, "whos_gunning", d6, rng)?;
    let boss_relationship = roll_sub_table(role_tables, "boss_relationship", d6, rng)?;

    Ok(RoleLifepath::Exec(ExecLifepath {
        corp_type,
        division,
        corp_ethics,
        corp_location,
        whos_gunning,
        boss_relationship,
    }))
}

/// Roll the Fixer lifepath (pp.66–67).
///
/// "Got a Partner or Work Alone?" is choose-only on p.66; defaulted to
/// "Work Alone" for the roller. See pp.43-69.
fn roll_fixer(role_tables: &RoleLifepathTables, rng: &mut Rng) -> Result<RoleLifepath, RulesError> {
    let fixer_type = roll_sub_table(role_tables, "fixer_type", d10, rng)?;
    let office = roll_sub_table(role_tables, "office", d6, rng)?;
    let side_clients = roll_sub_table(role_tables, "side_clients", d6, rng)?;
    let whos_gunning = roll_sub_table(role_tables, "whos_gunning", d6, rng)?;
    let partner = roll_sub_table(role_tables, "partner", d6, rng)?;

    Ok(RoleLifepath::Fixer(FixerLifepath {
        fixer_type,
        partner_or_alone: "Work Alone".to_string(),
        partner,
        office,
        side_clients,
        whos_gunning,
    }))
}

/// Roll the Nomad lifepath (pp.68–69).
///
/// "Is Your Pack Based on Land, Air, or Sea?" is choose-only on p.68.
/// Defaults to "Land" — rolling the 1d10 `nomad_land` sub-table.
/// A player-facing UI should let the player choose; air/sea paths would roll
/// `nomad_air` / `nomad_sea` (1d6) instead. See pp.43-69.
fn roll_nomad(role_tables: &RoleLifepathTables, rng: &mut Rng) -> Result<RoleLifepath, RulesError> {
    let pack_size = roll_sub_table(role_tables, "pack_size", d6, rng)?;
    // Default to Land — rolls the 1d10 nomad_land sub-table. See p.68.
    let pack_business = roll_sub_table(role_tables, "nomad_land", d10, rng)?;
    let personal_role = roll_sub_table(role_tables, "personal_role", d6, rng)?;
    let philosophy = roll_sub_table(role_tables, "philosophy", d6, rng)?;
    let whos_gunning = roll_sub_table(role_tables, "whos_gunning", d6, rng)?;

    Ok(RoleLifepath::Nomad(NomadLifepath {
        pack_size,
        land_air_sea: "Land".to_string(),
        pack_business,
        personal_role,
        philosophy,
        whos_gunning,
    }))
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use rand::SeedableRng;
    use std::path::PathBuf;

    /// Workspace-root-relative path to the lifepath content directory.
    fn lifepath_dir() -> PathBuf {
        let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        p.pop(); // crates/rules -> crates
        p.pop(); // crates -> repo root
        p.push("content");
        p.push("tables");
        p.push("lifepath");
        p
    }

    /// Acceptance test: every required field is populated after a roll.
    ///
    /// See WP-504 acceptance tests.
    #[test]
    fn test_lifepath_complete() {
        let mut rng = Rng::seed_from_u64(42);
        let lp = roll_lifepath(Role::Solo, &lifepath_dir(), &mut rng)
            .expect("roll_lifepath must succeed for Solo");

        assert!(
            !lp.cultural_region.is_empty(),
            "cultural_region must be populated"
        );
        assert!(
            !lp.language_spoken.is_empty(),
            "language_spoken must be populated"
        );
        assert!(!lp.personality.is_empty(), "personality must be populated");
        assert!(
            !lp.clothing_style.is_empty(),
            "clothing_style must be populated"
        );
        assert!(!lp.hairstyle.is_empty(), "hairstyle must be populated");
        assert!(
            !lp.affectations.is_empty(),
            "affectations must be populated"
        );
        assert!(!lp.motivation.is_empty(), "motivation must be populated");
        assert!(!lp.life_goal.is_empty(), "life_goal must be populated");
        assert!(
            !lp.family_background.original_background.is_empty(),
            "family_background.original_background must be populated"
        );
        assert!(
            !lp.family_crisis.is_empty(),
            "family_crisis must be populated"
        );
        assert!(
            !lp.friends.is_empty(),
            "friends must have at least one entry"
        );
        assert!(
            !lp.enemies.is_empty(),
            "enemies must have at least one entry"
        );
        assert!(
            !lp.tragic_loves.is_empty(),
            "tragic_loves must have at least one entry"
        );
        assert!(
            matches!(lp.role_specific, RoleLifepath::Solo(_)),
            "role_specific must be Solo for a Solo roll"
        );
        if let RoleLifepath::Solo(ref s) = lp.role_specific {
            assert!(!s.solo_type.is_empty(), "solo_type must be populated");
            assert!(
                !s.moral_compass.is_empty(),
                "moral_compass must be populated"
            );
            assert!(!s.whos_gunning.is_empty(), "whos_gunning must be populated");
            assert!(
                !s.operational_territory.is_empty(),
                "operational_territory must be populated"
            );
        }
    }

    /// Acceptance test: a Solo roll produces the Solo lifepath table, not the
    /// Rockerboy's. See WP-504 acceptance tests.
    #[test]
    fn test_lifepath_role_specific_matches_role() {
        let mut rng_solo = Rng::seed_from_u64(1);
        let lp_solo = roll_lifepath(Role::Solo, &lifepath_dir(), &mut rng_solo)
            .expect("Solo roll must succeed");
        assert!(
            matches!(lp_solo.role_specific, RoleLifepath::Solo(_)),
            "Solo role must produce RoleLifepath::Solo"
        );

        let mut rng_rock = Rng::seed_from_u64(2);
        let lp_rock = roll_lifepath(Role::Rockerboy, &lifepath_dir(), &mut rng_rock)
            .expect("Rockerboy roll must succeed");
        assert!(
            matches!(lp_rock.role_specific, RoleLifepath::Rockerboy(_)),
            "Rockerboy role must produce RoleLifepath::Rockerboy"
        );
    }

    /// Acceptance test: at least one friend, one enemy, and one tragic love
    /// each have names. See WP-504 acceptance tests.
    #[test]
    fn test_friends_enemies_have_names() {
        let mut rng = Rng::seed_from_u64(99);
        let lp = roll_lifepath(Role::Netrunner, &lifepath_dir(), &mut rng)
            .expect("roll_lifepath must succeed for Netrunner");

        let first_friend = lp.friends.first().expect("must have at least one friend");
        assert!(
            !first_friend.name.is_empty(),
            "first friend must have a name"
        );

        let first_enemy = lp.enemies.first().expect("must have at least one enemy");
        assert!(!first_enemy.name.is_empty(), "first enemy must have a name");

        let first_lover = lp
            .tragic_loves
            .first()
            .expect("must have at least one tragic love");
        assert!(
            !first_lover.name.is_empty(),
            "first tragic lover must have a name"
        );
    }

    /// Acceptance test: same seed produces the same Lifepath (determinism).
    /// See WP-504 acceptance tests.
    #[test]
    fn test_lifepath_deterministic_with_seed() {
        let seed = 7777;
        let dir = lifepath_dir();

        let mut rng_a = Rng::seed_from_u64(seed);
        let lp_a = roll_lifepath(Role::Tech, &dir, &mut rng_a).expect("first roll must succeed");

        let mut rng_b = Rng::seed_from_u64(seed);
        let lp_b = roll_lifepath(Role::Tech, &dir, &mut rng_b).expect("second roll must succeed");

        assert_eq!(lp_a, lp_b, "same seed must produce identical Lifepath");
    }

    /// Sanity: all ten roles can be rolled without errors.
    #[test]
    fn test_all_roles_roll_successfully() {
        let dir = lifepath_dir();
        let roles = [
            Role::Rockerboy,
            Role::Solo,
            Role::Netrunner,
            Role::Tech,
            Role::Medtech,
            Role::Media,
            Role::Lawman,
            Role::Exec,
            Role::Fixer,
            Role::Nomad,
        ];
        for (seed, role) in roles.iter().enumerate() {
            let mut rng = Rng::seed_from_u64(seed as u64);
            roll_lifepath(*role, &dir, &mut rng)
                .unwrap_or_else(|e| panic!("roll_lifepath failed for {:?}: {e}", role));
        }
    }

    /// Sanity: friend, enemy, and tragic-love notes are non-empty and beacon
    /// kinds are correct.
    #[test]
    fn test_relationship_beacons_have_notes() {
        let mut rng = Rng::seed_from_u64(12345);
        let lp = roll_lifepath(Role::Exec, &lifepath_dir(), &mut rng).expect("roll must succeed");

        for f in &lp.friends {
            assert!(!f.note.is_empty(), "friend note must be non-empty");
            assert_eq!(f.kind, BeaconKind::Friend);
        }
        for e in &lp.enemies {
            assert!(!e.note.is_empty(), "enemy note must be non-empty");
            assert_eq!(e.kind, BeaconKind::Enemy);
        }
        for l in &lp.tragic_loves {
            assert!(!l.note.is_empty(), "tragic love note must be non-empty");
            assert_eq!(l.kind, BeaconKind::Lover);
        }
    }
}
